server:
  port: 8500
  servlet:
    context-path: /

spring:
  application:
    name: platform-server
  profiles:
    active: druid
    
#  security:
#    user:
#      name: user
#      password: 123456

  redis:
    host: 101.201.254.58
    port: 6379
    password: p@ssw0rd

  cache:
    type: redis

mybatis-plus:
  mapper-locations: classpath:mapper/**/*.xml
  map-underscore-to-camel-case: true
  
logging:
  level:
    cn.liuw.platform.db.mapper : debug
  file:
    path: D:\Home\demo